### ISSUE TITLE
`once` and `doOnce` do not work

### ISSUE THREAD

**Issue by beef331** [archnim/sunk#1]
They take in a non `var bool` so the `bool` is copied by value meaning that `cond` will never change. A possible change that is memory unsafe is the following: 

```nim
proc once*(cond: var bool, todo: proc ()) =
  let cond = cond.addr
  let p = proc () {.async.} =
    while not cond[]:
      await sleepAsync(5)
    todo()

  discard p()
```

```nim
template once*(cond: var bool, todo: proc ()) =
  let p = proc () {.async.} =
    while not cond:
      await sleepAsync(5)
    todo()

  discard p()
```

Is a memory save version but uses a template. 

```nim
proc once*(cond: ref bool, todo: proc ()) =
  let p = proc () {.async.} =
    while not cond[]:
      await sleepAsync(5)
    todo()

  discard p()
```
Is a memory safe method but uses a `ref bool`.

**Comment by archnim** [comment]
Oh yes ! I didn't took notice of it because the tests I did were in the same file than the code. I've fixed it. Just uninstall and install it.
